export const ACTIVE_QUEST_PREFIX = "ACTIVE QUEST"

export function activeQuestContext(quest, { instructionAuditCurrent = true } = {}) {
  const instructionAudit = quest.instructionAudit && instructionAuditCurrent
    ? `\n\nQUEST INSTRUCTION PREFLIGHT\n\nReadiness: ${quest.instructionAudit.readiness.toUpperCase()}\nReviewed: ${quest.instructionAudit.reviewedSources.join("; ") || "No instruction sources recorded"}\nRisks: ${quest.instructionAudit.risks.map((risk) => `[${risk.severity}] ${risk.source}: ${risk.trigger} → ${risk.effect}. Mitigation: ${risk.mitigation}`).join("\n") || "No premature-stop risks found."}\n\nFollow all applicable higher-priority instructions. The Quest does not override them.${quest.instructionAudit.readiness === "blocked" ? " Do not begin or resume implementation until the user resolves the blocking conflict." : " Before work, account for every warning in the execution plan so it does not cause an avoidable premature stop."}`
    : `\n\nQUEST PREFLIGHT REQUIRED\n\n${quest.instructionAudit ? "Applicable AGENTS.md or CLAUDE.md files changed since the saved audit. " : ""}Do not begin substantive Quest work yet. First inspect all applicable AGENTS.md, CLAUDE.md, project rules, skill instructions, and visible higher-priority instructions for conditions that require stopping, asking the user, limiting retries, reporting and returning, or abandoning work after a tool failure. Save the result with quest_instruction_audit and warn the user about any premature-stop risk.`

  const checkpoint = quest.checkpoint
    ? `\n\nIN-FLIGHT CHECKPOINT\n\nSummary: ${quest.checkpoint.summary}\nCompleted: ${quest.checkpoint.completed.join("; ") || "None recorded"}\nCurrent step: ${quest.checkpoint.currentStep}\nNext action: ${quest.checkpoint.nextAction}\nRemaining: ${quest.checkpoint.remaining.join("; ") || "None recorded"}\nBlockers: ${quest.checkpoint.blockers.join("; ") || "None"}\nVerification: ${quest.checkpoint.verification?.join("; ") || "None recorded"}\n\nResume from this checkpoint without asking the user to restate the task. Do not stop merely because context was compacted or a prior turn reached its context limit. On the next model turn, re-inspect repository state, continue the next action, and update or clear the checkpoint as work advances.`
    : ""

  const plan = quest.plan
    ? `\n\nQUEST PLAN\n\n${quest.plan.map((item) => `- [${item.status}] (${item.priority}) ${item.id}: ${item.content}`).join("\n")}\n\nSynchronize this canonical plan to OpenCode's visible sidebar with the todowrite tool at the start of this turn if the session list is absent or differs. Keep the same IDs, content, statuses, and priorities. Maintain at most one in_progress item, mark items completed immediately when verified, and persist every sidebar status change back with quest_plan. The durable Quest plan is authoritative across sessions and compaction.`
    : `\n\nQUEST PLAN REQUIRED\n\nFirst replace any stale OpenCode todowrite list with the new objective's plan. After instruction preflight passes and before substantive multi-step work, create a concise ordered plan, persist it with quest_plan, and call OpenCode's todowrite tool with the identical items so the checklist appears in the sidebar.`

  const executionContract = `\n\nQUEST EXECUTION CONTRACT\n\nWhen working toward this Quest, verify the exact target path before editing and preserve recoverability before broad or structural changes. A compile/test failure, unfamiliar code, wrong edit, or context pressure is not by itself a blocker. Inspect the current file and diff, diagnose the first error from the current state, make the smallest reversible edit, and verify again. Never replace an existing source file wholesale to escape a local error.${quest.checkpoint ? " The Quest is in progress: continue until the current requested task is complete or a genuine blocker requires user input or new authority. Refresh the checkpoint after milestones and failures. Do not respond only with a failure report while safe recovery work remains." : " Before long or risky work, create an in-flight checkpoint with the exact next action."}`

  return `${ACTIVE_QUEST_PREFIX}\n\n${quest.objective}\n\nTreat this as the persistent high-level objective for the current project. The user's current message is the immediate task, but decisions should remain consistent with this Quest unless the user explicitly changes or clears it.${instructionAudit}${plan}${checkpoint}${executionContract}`
}
